CREATE TABLE project_settings (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,
    require_mfa BOOLEAN NOT NULL DEFAULT FALSE,
    session_timeout_hours INTEGER NOT NULL DEFAULT 24,
    ip_whitelist TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);