logging:
  level:
    org.flywaydb: DEBUG
spring:
  application:
    name: feature-flags
  datasource:
    url: jdbc:postgresql://localhost:5432/feature_flags
    username: flags_user
    password: flags_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-on-validation-error: true

server:
  port: 8080

jwt:
  secret: "dGhpc2lzYXRlc3RzZWNyZXRrZXlmb3Jqd3R0aGF0aXNhdGxlYXN0MzJieXRlc2xvbmc="
  issuer: "mozhno"
  access-token-ttl-minutes: 60