name: Documentation
description: Улучшить или исправить документацию
labels: [docs, triage]
body:
  - type: textarea
    id: what
    attributes:
      label: Что нужно изменить?
      description: Какая страница, секция, файл требует изменений?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Почему?
      description: Что сейчас неправильно или отсутствует?
    validations:
      required: true
